"""add reminder contacts and contract fields

Revision ID: 78d64cba9055
Revises: 
Create Date: 2026-06-08 10:19:54.061289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d64cba9055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_karyawan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tanggal_berakhir_kontrak', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('tanggal_berakhir_kontrak')
        batch_op.drop_column('status_karyawan')

    # ### end Alembic commands ###
